/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kube.grpc.hello;

import io.grpc.stub.StreamObserver;

import org.junit.Test;
import static org.junit.Assert.*;

public class HelloWorldServiceTest {
    @Test public void testServiceHasSayHello() {
        assertNotNull("app should have a greeting", "yes");
    }
}
